# Generated by Django 5.0.6 on 2024-06-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_data', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('residents_count', models.PositiveIntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='residents.house')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_space', to='residents.house')),
                ('reserved_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_space', to='residents.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_ownership', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='residents.apartment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='residents.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='residents.resident')),
            ],
        ),
    ]
