# Generated by Django 5.0.6 on 2024-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_remove_apartment_residents_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='номер'),
        ),
    ]
